- dnf:
    name: ["python3", "python3-pip"]
    state: present
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes
- package:
    name: python3-pip
    state: present
  ignore_errors: yes
- pip:
    name: ["dnsimple", "dataclasses", "dnspython"]
    executable: pip3
  become: true
  ignore_errors: yes
